language: cpp

osx_image: xcode7.3
env:
        - PYTHON=/usr/local/bin/python
        - JPEG=/usr/local/opt/mozjpeg
        - PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
        - JOBS="`sysctl -n hw.ncpu`"
        - PATH="/usr/local/opt/ccache/libexec:$PATH"
cache: ccache
before_install:
        - brew tap homebrew/science
        - brew update
        - brew install ccache pkg-config automake
        - brew install --ignore-dependencies gtk-doc
        - brew reinstall
          gobject-introspection
          fftw mozjpeg libexif
          libpng webp libtiff
          swig imagemagick
          cfitsio libmatio
          orc little-cms2 poppler
          pango libgsf openslide
          librsvg giflib openexr
          python pygobject3
          vips gtkmm

before_script:
  - ./autogen.sh
    --disable-dependency-tracking
    --with-jpeg-includes=$JPEG/include
    --with-jpeg-libraries=$JPEG/lib
  - make -j$JOBS -s V=0
script:
  - make -Ctest -j$JOBS -s V=0 VERBOSE=1 check
