language: cpp
os: osx
osx_image: xcode7.3
env:
        - PYTHON=/usr/local/bin/python
          JPEG=/usr/local/opt/mozjpeg
          PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
          JOBS="`sysctl -n hw.ncpu`"
          PATH="/usr/local/opt/ccache/libexec:$PATH"
cache: ccache
before_install:
        - brew tap homebrew/science
        - brew update
        - brew install ccache pkg-config automake
        - brew install --ignore-dependencies gtk-doc
        - brew reinstall   gobject-introspection
        - brew reinstall   gobject-introspection
        - brew reinstall   fftw
        - brew info   fftw
        - brew reinstall  mozjpeg
        - brew info  mozjpeg
        - brew reinstall  libexif
        - brew info  libexif
        - brew reinstall   libpng
        - brew info   libpng
        - brew reinstall  webp
        - brew info  webp
        - brew reinstall  libtiff
        - brew info  libtiff
        - brew reinstall   swig
        - brew info   swig
        - brew reinstall  imagemagick
        - brew info  imagemagick
        - brew reinstall   cfitsio
        - brew info   cfitsio
        - brew reinstall  libmatio
        - brew info  libmatio
        - brew reinstall   orc
        - brew info   orc
        - brew reinstall  little-cms2
        - brew info  little-cms2
        - brew reinstall  poppler
        - brew info  poppler
        - brew reinstall   pango
        - brew info   pango
        - brew reinstall  libgsf
        - brew info  libgsf
        - brew reinstall  openslide
        - brew info  openslide
        - brew reinstall   librsvg
        - brew info   librsvg
        - brew reinstall  giflib
        - brew info  giflib
        - brew reinstall  openexr
        - brew info  openexr
        - brew reinstall   python
        - brew info   python
        - brew reinstall  pygobject3
        - brew info  pygobject3
        - brew reinstall   gexiv2
        - brew info   gexiv2
        - brew reinstall  gtk+
        - brew info  gtk+
        - brew reinstall  pygtk
        - brew info  pygtk
        - brew reinstall  gtkmm 
        - brew info  gtkmm 
        - brew reinstall  gtk-mac-integration
        - brew info  gtk-mac-integration
        - brew reinstall  pugixml
        - brew info  pugixml
        - brew reinstall  vips
        - brew info  vips
          

before_script:
#  - brew info gtk-mac-integration
  - cd build
#  - git clone -b v8.4.2 --depth 1 https://github.com/jcupitt/libvips.git libvips
#  - cd libvips
#  - ./autogen.sh
#    --disable-dependency-tracking
#    --with-jpeg-includes=$JPEG/include
#    --with-jpeg-libraries=$JPEG/lib
#  - make -j$JOBS -s V=0
#  - make install
#  - cd ..
#  - rm -rf libvips
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_PREFIX=/usr/local -DBUNDLED_LENSFUN=ON ..
  - travis_wait 50 make -j2
script:
  - make install
