language: generic

compiler:
    - g++

sudo: required

dist: trusty

addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64
    - python3
    - python3-pip
    - python3-docutils
    - rpm2cpio
    - libfile-mimeinfo-perl

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    
before_script:
    - cd build
    - wget https://pypi.python.org/packages/f4/ea/4faf47f49928ba276fc555b4ebd8432a77494a63fd7ee25b6bccb5820c67/crossroad-0.6.tar.gz
    - tar xzvf crossroad-0.6.tar.gz
    - cd crossroad-0.6 && ./setup.py install --prefix=$HOME/inst && cd ..
    #- sudo pip3 install crossroad
    - cat $HOME/inst/share/crossroad/scripts/cmake/toolchain-w64.cmake
    - sudo echo "" >> $HOME/inst/share/crossroad/scripts/cmake/toolchain-w64.cmake
    - sudo echo "SET(PKG_CONFIG_EXECUTABLE x86_64-w64-mingw32-pkg-config)" >> $HOME/inst/share/crossroad/scripts/cmake/toolchain-w64.cmake
    - $HOME/inst/bin/crossroad --help w64
    - $HOME/inst/bin/crossroad w64 phf-build --run ../windows/dep-install.sh
    #- $HOME/inst/bin/crossroad w64 phf-build --run ../windows/dep-build.sh
    #- $HOME/inst/bin/crossroad w64 phf-build --run ../windows/phf-build.sh
    #- $HOME/inst/bin/crossroad w64 phf-build --run ../windows/package-w64.sh
