language: cpp
os: osx
osx_image: xcode7.3
env:
        - PYTHON=/usr/local/bin/python
          JPEG=/usr/local/opt/mozjpeg
          PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
          JOBS="`sysctl -n hw.ncpu`"
          PATH="/usr/local/opt/ccache/libexec:$PATH"
cache: ccache
before_install:
          
install:
# - stty rows 40 columns 80 # set rows, columns in terminal
 - export COLUMNS=80
 - export ROWS=40
 - wget https://distfiles.macports.org/MacPorts/MacPorts-2.3.3.tar.bz2
 - tar xvfj MacPorts-2.3.3.tar.bz2
 - cd MacPorts-2.3.3
 - ./configure &&  sudo make install
 - export PATH=/opt/local/bin:$PATH
 - sudo mv /usr/local /usr/_local
 - sudo port -v selfupdate
 - sudo port install gtk2 -x11 +quartz +bundle
 - sudo port install gtkmm -x11 +quartz
 - sudo port install vips
 - sudo port install gexiv2
 - sudo port install pugixml
 - sudo port install gtk-osx-application-gtk2 
 - sudo mv /usr/_local /usr/local

before_script:
#  - brew info gtk-mac-integration
  - cd ${TRAVIS_BUILD_DIR}/build
#  - git clone -b v8.4.2 --depth 1 https://github.com/jcupitt/libvips.git libvips
#  - cd libvips
#  - ./autogen.sh
#    --disable-dependency-tracking
#    --with-jpeg-includes=$JPEG/include
#    --with-jpeg-libraries=$JPEG/lib
#  - make -j$JOBS -s V=0
#  - make install
#  - cd ..
#  - rm -rf libvips
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_PREFIX=/usr/local -DBUNDLED_LENSFUN=ON ..
#  - travis_wait 50 make -j2
#  - make -j1 VERBOSE=1
  - make -j2
  - make install
  - cd ..
script:
  - cd osx
  - ./package-photoflow.sh
