language: generic

compiler:
    - g++

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - g++
      - gettext
      - intltool
      - gir1.2-gtk-3.0
      - libgtk2.0-dev
      - liblcms2-dev
      - libpng12-dev
      - python-dev
      - python-gi-dev
      - python-gi-cairo
      - python-nose
      - python-numpy
      - automake
      - gtk-doc-tools
      - gobject-introspection
      - libfftw3-dev-
      - libjpeg-turbo8-dev
      - libpng12-dev
      - libwebp-dev
      - libtiff4-dev
      - libxml2-dev
      - swig
      - libmagick++-dev
      - bc
      - libcfitsio3-dev
      - libgsl0-dev
      - libmatio-dev
      - liborc-0.4-dev
      - liblcms2-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libgif-dev
      - libpango1.0-dev
      - python-dev
      - libgtk2.0-dev
      - libfftw3-dev
      - libexiv2-dev
      - libgexiv2-dev
      - libsigc++-2.0-dev
      - libpixman-1-dev
      - libpango1.0-dev
      - libpangoft2-1.0-0
      - libglib2.0-dev
      - libglibmm-2.4-dev
      - libgtkmm-2.4-dev
      - libpugixml-dev


before_script:
    - cd build
    - export PKG_CONFIG_PATH=/app/lib/pkgconfig:${PKG_CONFIG_PATH}
    - export LD_LIBRARY_PATH=/app/lib:${LD_LIBRARY_PATH}
    - git clone -b v8.4.2 --depth 1 https://github.com/jcupitt/libvips.git libvips
    - cd libvips
    - ./autogen.sh
    - FLAGS="-O2 -msse4.2 -ffast-math -ftree-vectorize" CFLAGS="${FLAGS}" CXXFLAGS="${FLAGS} -fpermissive" ./configure --prefix=/app --disable-gtk-doc --disable-gtk-doc-html --disable-introspection --enable-debug=no --without-python --without-magick --without-libwebp --enable-pyvips8=no --enable-shared=yes --enable-static=no
    - make -j$JOBS
    - sudo make install
    - cd ..
    - rm -rf libvips
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/app -DINSTALL_PREFIX=/app -DBUNDLED_LENSFUN=ON ..
    - make -j$JOBS
    - sudo make install
    - cd ..
    - sudo rm -fr PhotoFlow

script:
    - bash -ex appimage/appimage.sh
