language: generic

#env:
matrix:
    allow_failures:
        - env: TARGET_SYSTEM=Windows
    include:
        - os: linux
          dist: trusty
          compiler: g++
          sudo: required
          dist: trusty
          env: TARGET_SYSTEM=Linux
          addons:
            apt:
              sources:
                #- sourceline: 'ppa:dhor/myway'
                    - sourceline: 'ppa:otto-kesselgulasch/gimp-edge'
              packages:
                - g++
                - gettext
                - intltool
                - gir1.2-gtk-3.0
                - libgtk2.0-dev
                - liblcms2-dev
                - libpng12-dev
                - python-dev
                - python-gi-dev
                - python-gi-cairo
                - python-nose
                - python-numpy
                - automake
                - gtk-doc-tools
                - gobject-introspection
                - libfftw3-dev
                - libjpeg-turbo8-dev
                - libpng12-dev
                - libwebp-dev
                - libtiff4-dev
                - libxml2-dev
                - swig
                - libmagick++-dev
                - bc
                - libcfitsio3-dev
                - libgsl0-dev
                - libmatio-dev
                - liborc-0.4-dev
                - libpoppler-glib-dev
                - librsvg2-dev
                - libgif-dev
                - python-dev
                - libsigc++-2.0-dev
                - libpixman-1-dev
                - libpango1.0-dev
                - libpangoft2-1.0-0
                - libglib2.0-dev
                - libglibmm-2.4-dev
                - libgtkmm-2.4-dev
                - libpugixml-dev
                - gtk2-engines-pixbuf
                - zenity
          before_script:
              #- cd non_existent_dir
              - cd build
              - export PKG_CONFIG_PATH=/app/lib/pkgconfig:${PKG_CONFIG_PATH}
              - export LD_LIBRARY_PATH=/app/lib:${LD_LIBRARY_PATH}
              #- git clone -b v8.4.1 --depth 1 https://github.com/jcupitt/libvips.git libvips
              #- git clone https://github.com/jcupitt/libvips.git libvips
              #- cd libvips
              # revert to git version of 9/2/2017
              #- git reset --hard 6691e07d72c284468c77f4a95139ac43bf0cdc6f
              #- wget http://www.vips.ecs.soton.ac.uk/supported/8.4/vips-8.4.5.tar.gz
              #- tar xzvf vips-8.4.5.tar.gz
              #- cd vips-8.4.5
              - wget https://github.com/jcupitt/libvips/releases/download/v8.5.6/vips-8.5.6.tar.gz
              - tar xzvf vips-8.5.6.tar.gz
              - cd vips-8.5.6
              - ./autogen.sh
              - FLAGS="-g -O2 -march=nocona -mno-sse3 -mtune=generic -ftree-vectorize" CFLAGS="${FLAGS}" CXXFLAGS="${FLAGS} -fpermissive" ./configure --prefix=/app --disable-gtk-doc --disable-gtk-doc-html --disable-introspection --enable-debug=no --without-python --without-magick --without-libwebp --enable-pyvips8=no --enable-shared=yes --enable-static=no
              - make -j2
              - sudo make install
              - cd ..
              - rm -rf libvips
              - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/app -DINSTALL_PREFIX=/app -DBUNDLED_LENSFUN=ON ..
              - 'if [ x"${TRAVIS_BRANCH}" != "xmaster" ]; then
                  echo "#include <version.hh>" > ../src/version.cc || travis_terminate 1;
                  echo "const char* PF::version_string = \"PhotoFlow git-${TRAVIS_BRANCH}-${TRAVIS_COMMIT}\";" >> ../src/version.cc || travis_terminate 1;
                fi'
              - make -j2
              - sudo make install
              - cd ..
              #- sudo rm -fr PhotoFlow
          script:
              - cd $TRAVIS_BUILD_DIR
              - pwd
              - bash appimage/appimage.sh
          after_success:
              - cd $HOME
              - cd $TRAVIS_BUILD_DIR
              - cd ..
              - pwd
              - ls -lh
              - ls -lh out/* # Assuming you have some files in out/ that you would like to upload
              #- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
              #- wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload.sh
              - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
              - 'if [ x"${TRAVIS_BRANCH}" = "xstable" ]; then
                  bash  ./upload_rotate.sh "continuous" out/*;
                fi'
              - 'if [ x"${TRAVIS_BRANCH}" = "xlinear_gamma" ]; then
                  bash  ./upload_rotate.sh "unstable" out/*;
                fi'
              - find /usr -name gconv
        - os: linux
          dist: trusty
          compiler: g++
          sudo: required
          dist: trusty
          env: TARGET_SYSTEM=Windows
          before_script:
            - cd non_existent_dir
            - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            - sudo add-apt-repository ppa:adrozdoff/mingw -y
            - sudo apt-get update
            - sudo apt-get install gcc-5-mingw-w64 g++-5-mingw-w64 binutils-mingw-w64-x86-64 python3 python3-docutils rpm2cpio libfile-mimeinfo-perl
            - sudo ln -s /usr/bin/i686-w64-mingw32-gcc-5 /usr/bin/i686-w64-mingw32-gcc
            - sudo ln -s /usr/bin/i686-w64-mingw32-g++-5 /usr/bin/i686-w64-mingw32-g++
            - ls -l /usr/bin/i686-w64-mingw32*
            - cd build
            #- wget https://pypi.python.org/packages/f4/ea/4faf47f49928ba276fc555b4ebd8432a77494a63fd7ee25b6bccb5820c67/crossroad-0.6.tar.gz
            #- tar xzvf crossroad-0.6.tar.gz
            #- find crossroad-0.6 -type f -print0 | xargs -0 sed -i 's/openSUSE_42.1/openSUSE_Leap_42.1/g'
            #- cd crossroad-0.6 && ./setup.py install --prefix=$HOME/inst && cd ..
            - wget https://pypi.python.org/packages/c4/3e/f6a66a52cdd3340a9ae5a581fbc7ccffdfabe307e50282794bd7d93e5420/crossroad-0.7.tar.gz
            - tar xzvf crossroad-0.7.tar.gz
            #- find crossroad-0.7 -type f -print0 | xargs -0 sed -i 's/openSUSE_42.1/openSUSE_Leap_42.1/g'
            - cd crossroad-0.7 && ./setup.py install --prefix=$HOME/inst && cd ..
            - cat $HOME/inst/share/crossroad/scripts/cmake/toolchain-w32.cmake
            - echo "" >> $HOME/inst/share/crossroad/scripts/cmake/toolchain-w32.cmake
            - echo "SET(PKG_CONFIG_EXECUTABLE i686-w64-mingw32-pkg-config)" >> $HOME/inst/share/crossroad/scripts/cmake/toolchain-w32.cmake
            - $HOME/inst/bin/crossroad --help w32
            - $HOME/inst/bin/crossroad w32 phf-build --run ../windows/dep-install.sh
            - $HOME/inst/bin/crossroad w32 phf-build --run ../windows/dep-build.sh
            - $HOME/inst/bin/crossroad w32 phf-build --run ../windows/phf-build.sh
            - $HOME/inst/bin/crossroad w32 phf-build --run ../windows/package-w32.sh
            #- wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload.sh
            - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            - 'if [ x"${TRAVIS_BRANCH}" = "xstable" ]; then
                bash  ./upload_rotate.sh "continuous" photoflow*.zip
              fi'
            - 'if [ x"${TRAVIS_BRANCH}" = "xlinear_gamma" ]; then
                bash  ./upload_rotate.sh "unstable" photoflow*.zip
              fi'
        - os: linux
          dist: trusty
          compiler: g++
          sudo: required
          dist: trusty
          env: TARGET_SYSTEM=Windows
          before_script:
            #- cd non_existent_dir
            - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            - sudo add-apt-repository ppa:adrozdoff/mingw -y
            - sudo apt-get update
            - sudo apt-get install gcc-5-mingw-w64 g++-5-mingw-w64 binutils-mingw-w64-x86-64 python3 python3-docutils rpm2cpio libfile-mimeinfo-perl
            - sudo ln -s /usr/bin/x86_64-w64-mingw32-gcc-5 /usr/bin/x86_64-w64-mingw32-gcc
            - sudo ln -s /usr/bin/x86_64-w64-mingw32-g++-5 /usr/bin/x86_64-w64-mingw32-g++
            - ls -l /usr/bin/x86_64-w64-mingw32*
            - cd build
            #- wget https://pypi.python.org/packages/f4/ea/4faf47f49928ba276fc555b4ebd8432a77494a63fd7ee25b6bccb5820c67/crossroad-0.6.tar.gz
            #- tar xzvf crossroad-0.6.tar.gz
            #- find crossroad-0.6 -type f -print0 | xargs -0 sed -i 's/openSUSE_42.1/openSUSE_Leap_42.1/g'
            #- cd crossroad-0.6 && ./setup.py install --prefix=$HOME/inst && cd ..
            - wget https://pypi.python.org/packages/c4/3e/f6a66a52cdd3340a9ae5a581fbc7ccffdfabe307e50282794bd7d93e5420/crossroad-0.7.tar.gz
            - tar xzvf crossroad-0.7.tar.gz
            #- find crossroad-0.7 -type f -print0 | xargs -0 sed -i 's/openSUSE_42.1/openSUSE_Leap_42.1/g'
            - cd crossroad-0.7 && ./setup.py install --prefix=$HOME/inst && cd ..
            - cat $HOME/inst/share/crossroad/scripts/cmake/toolchain-w64.cmake
            #- echo "" >> $HOME/inst/share/crossroad/scripts/cmake/toolchain-w64.cmake
            # - echo "SET(PKG_CONFIG_EXECUTABLE x86_64-w64-mingw32-pkg-config)" >> $HOME/inst/share/crossroad/scripts/cmake/toolchain-w64.cmake
            - $HOME/inst/bin/crossroad --help w64
            #- $HOME/inst/bin/crossroad w64 phf-build
            - pwd
            - cat ../windows/test_cmd.sh
            - ../windows/test_cmd.sh w64
            - ../windows/dep-install.sh w64
            - ../windows/dep-build.sh w64
            - ../windows/phf-build.sh w64
            #- $HOME/inst/bin/crossroad w64 phf-build --run $(pwd)/../windows/dep-install.sh
            #- $HOME/inst/bin/crossroad w64 phf-build --run ../windows/dep-build.sh
            #- $HOME/inst/bin/crossroad w64 phf-build --run ../windows/phf-build.sh
            - ../windows/package-w64.sh
            #- wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload.sh
            - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            - 'if [ x"${TRAVIS_BRANCH}" = "xstable" ]; then
                bash  ./upload_rotate.sh "continuous" photoflow*.zip
              fi'
            - 'if [ x"${TRAVIS_BRANCH}" = "xlinear_gamma" ]; then
                bash  ./upload_rotate.sh "unstable" photoflow*.zip
              fi'


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
