language: generic

matrix:
    include:
        - os: linux
          dist: trusty
          compiler: g++
          sudo: required
          services: docker
          dist: trusty
          addons:
            apt:
              packages:
                - g++
                - gettext
          before_script:
                - sudo docker build -f appimage/Dockerfile -t phf-appimage .
                - sudo docker run -it -v $(pwd):/sources phf-appimage scl enable devtoolset-3 '/sources/appimage/build.sh'

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    
