language: generic

#env:
matrix:
    allow_failures:
        - env: TARGET_SYSTEM=OSX
    include:
        - os: linux
          dist: trusty
          compiler: g++
          sudo: required
          services: docker
          env: TARGET_SYSTEM=Linux-GTK3
          before_script:
            - travis_wait 120 sleep infinity & sudo docker pull photoflow/docker-centos7-gtk
            - rm -rf appimage
            - git clone https://github.com/aferrero2707/pf-build-appimage.git appimage
            - sudo docker run -it -e USE_GTKMM3=OFF -v $(pwd):/sources photoflow/docker-centos7-gtk bash /sources/appimage/appimage-docker.sh
          after_success:
            - cd $TRAVIS_BUILD_DIR
            - ls -lh
            - bash appimage/package-appimage.sh
            - ls out/*
            - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            #- bash  ./upload_rotate.sh "continuous" out/*;
        - os: linux
          dist: trusty
          compiler: g++
          sudo: required
          dist: trusty
          env: TARGET_SYSTEM=Windows
          before_script:
            #- cd non_existent_dir
            - pwd
            - rm -rf windows && git clone https://github.com/aferrero2707/pf-build-win.git windows
            - sudo docker run -it -e "TRAVIS_BUILD_DIR=/sources" -e "TRAVIS_BRANCH=${TRAVIS_BRANCH}" -e "TRAVIS_COMMIT=${TRAVIS_COMMIT}" -v $(pwd):/sources photoflow/docker-zesty-mingw bash -c /sources/windows/package-w64.sh
            - # check if zip file was successfully created
            - # abort job with failure if not
            - ls photoflow-w64*.zip
          after_success:
            - cd $TRAVIS_BUILD_DIR
            - pwd
            #- wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload.sh
            - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            - 'if [ x"${TRAVIS_BRANCH}" = "xstable" ]; then
                bash  ./upload_rotate.sh "continuous" photoflow*.zip;
              fi'
            - 'if [ x"${TRAVIS_BRANCH}" = "xlinear_gamma" ]; then
                bash  ./upload_rotate.sh "unstable" photoflow*.zip;
              fi'
        - os: osx
          cache: ccache
          osx_image: xcode7.3
          env: 
          - TARGET_SYSTEM=OSX
            PATH="$HOME/homebrew/bin:$PATH"
            LD_LIBRARY_PATH="$HOME/homebrew/lib:$LD_LIBRARY_PATH"
            LIBRARY_PATH="$HOME/homebrew/lib:$LIBRARY_PATH"
            PYTHON=$HOME/homebrew/bin/python
            PKG_CONFIG_PATH=$HOME/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH
            JOBS="`sysctl -n hw.ncpu`"
            MACOSX_DEPLOYMENT_TARGET=10.8
            HOMEBREW_NO_AUTO_UPDATE=1
            #PATH=$HOME/homebrew/opt/python/libexec/bin:$HOME/homebrew/bin:$PATH
            #LD_LIBRARY_PATH=$HOME/homebrew/lib:$LD_LIBRARY_PATH
            #PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
            #JPEG=/usr/local/opt/mozjpeg
          before_script:
            - rm -rf osx
            - git clone https://github.com/aferrero2707/pf-build-osx.git osx
            - sudo mv /usr/local/bin /usr/local/bin_
            - sudo mv /usr/local/lib /usr/local/lib_
            - sudo mv /usr/local/opt /usr/local/opt_
            - $TRAVIS_BUILD_DIR/osx/dep-install.sh 5
            #- export PATH="/usr/local/opt/ccache/libexec:$PATH"
            - cd $TRAVIS_BUILD_DIR
            - mkdir -p build
            - cd build
            - cmake -DBUNDLED_LENSFUN=OFF -DBUNDLED_LENSFUN_DB=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$HOME/homebrew ..
            #- cmake -DBUNDLED_LENSFUN=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local ..
            - make -j 3
            - make install
            - cd $TRAVIS_BUILD_DIR/osx
            - ./package-photoflow-hb.sh
            #- wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            - 'if [ x"${TRAVIS_BRANCH}" = "xstable" ]; then
                bash  ./upload_rotate.sh "continuous" $HOME/photoflow-osx-*.dmg > /dev/null;
              fi'
            - 'if [ x"${TRAVIS_BRANCH}" = "xlinear_gamma" ]; then
                bash  ./upload_rotate.sh "unstable" $HOME/photoflow-osx-*.dmg > /dev/null;
              fi'


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
