language: cpp
os: osx
osx_image: xcode7.3
env:
        - PYTHON=/usr/local/bin/python
          JPEG=/usr/local/opt/mozjpeg
          PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
          JOBS="`sysctl -n hw.ncpu`"
          PATH="/usr/local/opt/ccache/libexec:$PATH"
          CASHER_TIME_OUT=600

cache:
  ccache: true
  directories:
    - $HOME/macports

before_install:
          
install:
# - stty rows 40 columns 80 # set rows, columns in terminal
 - export COLUMNS=80
 - export ROWS=40
 - sudo mv /usr/local/lib /usr/local/_lib
 - sudo mv /usr/local/include /usr/local/_include
 - export PATH=$HOME/macports/bin:$PATH
 - if [ ! -e $HOME/macports/bin/port ]; then
     wget https://distfiles.macports.org/MacPorts/MacPorts-2.3.3.tar.bz2;
     tar xvfj MacPorts-2.3.3.tar.bz2;
     cd MacPorts-2.3.3;
     ./configure --prefix=$HOME/macports && sudo make install;
     cd ..;
     sudo port -v selfupdate;
     fi
 - sudo port install libpng
 - sudo port install gnome-common
 - sudo port install docbook-xml
 - sudo port install perl5
 - sudo port install libxml2
 - sudo port install sqlite3
 - sudo port install python27
 - sudo port install glib2
 - sudo port install libffi
 - sudo port install readline
 - sudo port install boost
 - sudo port install openssl
 - sudo port install libtool
 - sudo port install source-highlight
 #- sudo port install 
 - sudo port install gtk-doc
 - sudo port install cairo
 - sudo port install gtk2 -x11 +quartz +bundle
 #- sudo port install gtkmm -x11 +quartz
 #- sudo port install vips
 #- sudo port install gexiv2
 #- sudo port install pugixml
 #- sudo port install gtk-osx-application-gtk2 
 - sudo mv /usr/local/_lib /usr/local/lib
 - sudo mv /usr/local/_include /usr/local/include

before_script:
#  - brew info gtk-mac-integration
  - cd ${TRAVIS_BUILD_DIR}/build
#  - git clone -b v8.4.2 --depth 1 https://github.com/jcupitt/libvips.git libvips
#  - cd libvips
#  - ./autogen.sh
#    --disable-dependency-tracking
#    --with-jpeg-includes=$JPEG/include
#    --with-jpeg-libraries=$JPEG/lib
#  - make -j$JOBS -s V=0
#  - make install
#  - cd ..
#  - rm -rf libvips
#  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_PREFIX=/usr/local -DBUNDLED_LENSFUN=ON ..
#  - travis_wait 50 make -j2
#  - make -j1 VERBOSE=1
#  - make -j2
#  - make install
  - cd ..
script:
  - cd osx 
#  - ./package-photoflow.sh
