language: generic

compiler:
    - g++

sudo: required

dist: trusty

addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64
    - python
    - python-dev

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    
before_script:
    - cd build
    - pip3 install crossroad

