language: generic

matrix:
    include:
        - os: linux
          dist: trusty
          compiler: g++
          sudo: required
          services: docker
          dist: trusty
          addons:
            apt:
              packages:
                - g++
                - gettext
          before_script:
                - sudo docker build -f appimage/Dockerfile -t phf-appimage .
                - sudo docker run -it phf-appimage ls /etc/redhat-release
                - cd build
                - export PKG_CONFIG_PATH=/app/lib/pkgconfig:${PKG_CONFIG_PATH}
                - export LD_LIBRARY_PATH=/app/lib:${LD_LIBRARY_PATH}

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    
