language: generic

compiler:
    - g++

sudo: required

dist: trusty

addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64
    - python3
    - python3-pip
    - python3-docutils
    - rpm2cpio
    - libfile-mimeinfo-perl

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    
before_script:
    - cd build
    - sudo pip3 install crossroad
    - cat /usr/local/share/crossroad/scripts/cmake/toolchain-w64.cmake
    - sudo echo "" >> /usr/local/share/crossroad/scripts/cmake/toolchain-w64.cmake
    - sudo echo "SET(PKG_CONFIG_EXECUTABLE x86_64-w64-mingw32-pkg-config)" >> /usr/local/share/crossroad/scripts/cmake/toolchain-w64.cmake
    - crossroad --help w64
    - crossroad w64 phf-build --run ../windows/build-w64.sh
