codecov:
  notify:
    require_ci_to_pass: true
    irc:
      default:
        server: chat.freenode.net
        channel: '#rawspeed'
coverage:
  precision: 2
  range: "0...100"
  round: down
  status:
    changes: false
    patch: false
    project: false
  ignore:
    - "test/.*"
    - "test/**"
    - "test/**/*"
    - "**/test/**/*"
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
comment:
  behavior: default
  layout: header, diff
  require_changes: false
